### ISSUE TITLE
document header token based auth

### ISSUE THREAD

**Issue by bparees** [openshift/jenkins-openshift-login-plugin#14] opened 2017-05-22 12:38 UTC
I'm not seeing anything in the readme that explains how to use the header token based auth flow (where you just provide your openshift token in a header with the request, rather than going through an oauth dance).

**Comment by gabemontero** [comment] 2017-05-22 13:39
Is it ok to put a link to where we explain it in the official docs?  Or do you want to move that explanation here and change the official docs to have a link to this readme?

**Comment by bparees** [comment] 2017-05-22 14:48
I think i'd prefer the latter.

**Comment by gabemontero** [comment] 2017-05-24 15:15
Actually I just brought up the readme, and the text is already there in the Primary Scenario section.  It is a duplicate of what is in the online docs today.  Starting on line 27.  Do you want me to add say a level 3 header or highlighted note of some sort to make it stand out? 

I can also still remove the duplicate verbiage in the online doc version, and just pass a link to the readme repo.

**Comment by bparees** [comment] 2017-05-24 15:33
Weird, I don't know why i didn't see that.  But yeah, a header would be useful, and linking from the official docs so we don't have to maintain the content in two places would also still be good.

**Closed** 2017-05-24 17:37 UTC
