### ISSUE TITLE
Getting Access Denied error

### ISSUE THREAD

**Issue by jim-minter** [openshift/jenkins-openshift-login-plugin#5] opened 2016-11-09 10:55 UTC
I'm getting the following error from Jenkins when navigating to the front page: "Access Denied \n demo is missing the Overall/Read permission".

This happens after successfully logging in, doing things in Jenkins, then leaving it idle for a while.
Chrome / Fedora / origin latest / upstream Jenkins image

When the access denied error happens, I can still navigate the OpenShift console fine (i.e. doesn't look like that session has expired).  Clicking 'log out' in Jenkins then logging back in again brings the Jenkins console back.

**Comment by jim-minter** [comment] 2016-11-09 10:55
@gabemontero ^^

**Comment by gabemontero** [comment] 2016-11-09 15:03
@jim-minter yep a common misstep, unless something unexpected happened.

We typically see this when someone logs into Jenkins with an ID other than what they ran `oc new-app` against to instantiate Jenkins.  The `demo` ID does not have permissions in the project Jenkins is running in.  As the prompt says, you must use your OpenShift credentials.

If you don't think this is your scenario, I'll need more details on how you set things up.  Thanks.

**Comment by jim-minter** [comment] 2016-11-09 15:50
No, I've been running as the demo user all along - no other user.  Jenkins created using the build admission plugin in namespace demo, user demo has admin role in that namespace.

**Comment by gabemontero** [comment] 2016-11-09 16:23
OK, then I'll either need a repro with trace or a debug version of the plugin to see what is being reported when we do the oauth self-sar for the "demo" user, or the precise steps you use to set up to see if I can repro and then debug.

Which approach do you prefer?

The `oc cluster up`, `oc new-app jenkins-ephemeral`, log into Jenkins with the `developer` ID has been working for everyone.

**Comment by jim-minter** [comment] 2016-11-09 17:36
Have also just pressed F5 on the Jenkins page and got redirected to `https://jenkins-demo.router.default.svc.cluster.local/login?from=%2F`, which is bad news because that page doesn't accept OpenShift credentials.

**Comment by gabemontero** [comment] 2016-11-09 18:40
That's a function of the root url for jenkins which gets back to how the route is constructed when bringing the cluster up, which gets back to how the cluster was brought up.

To debug, I'll reiterate:  do you want to gather debug data for me, or can you provide me the specific steps used to bring up the cluster so I can see if I can reproduce?

**Comment by gabemontero** [comment] 2016-11-10 15:26
Pending debug, as possible quick fix if this is related to what the oauth endpoints are providing us is [this](https://docs.openshift.org/latest/install_config/upgrading/manual_upgrades.html#updating-policy-definitions)

This is the first thing the oauth folks recommend when things are out of sync.

**Comment by jim-minter** [comment] 2016-11-10 17:52
OK, this reproduces it for me:
- oc cluster up
- oc create -f https://gist.githubusercontent.com/jim-minter/b4285b000b0e68a09c1bfc1db4b669e3/raw/f75d437d27bef2a534e28ab44132f8f14d4508b4/gistfile1.txt
- log in to openshift console as developer/developer
- wait for Jenkins to spin up automatically
- go to Jenkins console, authenticate with openshift developer/developer creds, allow permissions, you should see the nodejs-ex job
- oc delete bc nodejs-ex
- then without refreshing jenkins click nodejs-ex job in Jenkins console (yes, it's a stale link)
- get Access Denied / developer is missing the Overall/Read permission error [issue 1]
- then click log out in top right corner
- sometimes, this causes me to be redirected to https://jenkins-myproject.router.default.svc.cluster.local/login?from=%2F , where I cannot authenticate with my Openshift credentials (it's not the openshift oauth screen, it's the standard Jenkins credentials screen) [issue 2]

**Comment by gabemontero** [comment] 2016-11-10 18:08
Ah - the precise list of repro steps helps greatly.... @bparees ran into something similar re: issue 1.  Jenkins resets the login provider when deleting jobs, which the deleting of the jenkins pipeline build config will do.  The fix I put in for @bparees at the time fixed it for him.  But I developed some concern based on some results from others immediately afterward with that fix in that it was causing too much churn and making jenkins unstable, so I put some batching into it.  Perhaps we are hitting a timing window with this.

Your issue 2 builds from this.  We have not switched from the standard Jenkins credentials back to Oauth yet after the job delete did its switch.

Running through the scenario now ....

**Comment by gabemontero** [comment] 2016-11-10 18:12
Of course it did not occur for me when I tried it :-( ..... add validation for me at least to the timing aspect theory on this.

@jim-minter - would you still have the container log (i.e. docker logs <container id>) available from your instance to provide to me?

**Comment by jim-minter** [comment] 2016-11-10 18:19
@gabemontero logs at https://gist.github.com/jim-minter/0f8e6bf339746042ff1be2ff229920d1 - lmk if you want me to rerun with more than default logging (and remind me how please?)

**Comment by gabemontero** [comment] 2016-11-10 18:35
@jim-minter no, the default logging was sufficient.  The batching I was referring to appears to be the thing.  It took 40 seconds after you deleted the bc before the code switched back to Oauth.  I also have jenkins lifecycle listeners that fire but it looks like based on the timing of when they fire, they may not help (I think this explains to me why I have not seen it yet, and you seem to be seeing it intermittently based on your report in IRC).

I *think* I have an idea which could force the switch when the jenkins lifecycle listeners fire, but are still less aggressive on the per http request path.  Let's try that before I just reduce/eliminate the batching.

If I have a patch for you to try in the next 15 to 20 minutes, will you have time to try it out before you sign off for the day?

**Comment by gabemontero** [comment] 2016-11-10 18:37
(admittedly, might have to *reduce* the batching interval ... it is currently 1 minute)

**Comment by gabemontero** [comment] 2016-11-10 18:43
ahhhh ... git won't let me attach a file with a `.hpi` suffix.  I'll email to you @jim-minter

**Comment by gabemontero** [comment] 2016-11-10 18:55
Finally repro'ed !!   even with the patch I just sent @jim-minter .... looking at my local logs now.

**Comment by gabemontero** [comment] 2016-11-10 21:46
Unfortunately, the logs from my repro, after reducing the batch window I noted earlier, were not conclusive.  It appeared as if the security provider was updated, but user permissions were off.  Refreshes from the browser did not address.  However, I could log in from another browser OK.

The intermittent nature of the problem is hampering diagnosis.

That said, I believe I may have found a valid/supported way to persist the config to disk once we have determined that all the needed config values are obtainable from the master.  I'm prototyping now.  If it proves out, this will be the long term solution.

**Comment by gabemontero** [comment] 2016-11-10 22:31
Persisting config works.    This is addressed with commit https://github.com/openshift/jenkins-openshift-login-plugin/commit/26d08834e524d2d38d61c49573461c7dc296e8da

Closing out.  Look for v0.9 of openshift-login plugin in upcoming update to jenkins images.

**Closed by gabemontero** 2016-11-10 22:31 UTC

**Comment by gabemontero** [comment] 2016-11-11 04:58
@jim-minter the jenkins images on docker hub should be seeded with v0.9 of openshift-login ... if you get the chance git it a whirl - thanks

**Comment by jim-minter** [comment] 2016-11-11 09:41
@gabemontero looks like this problem is solved in the new image, but unfortunately overall that image is broken for me because of https://github.com/jenkinsci/openshift-sync-plugin/pull/18

**Comment by gabemontero** [comment] 2016-11-11 12:12
OK thanks for the update @jim-minter!  cool about the fix here, bummer
about the new issue in sync.
